### ISSUE TITLE
File changes randomly stop being detected.

### ISSUE THREAD

**Issue by DevAgu93** [EpicGamesExt/raddebugger#142]
https://github.com/EpicGames/raddebugger/assets/63572671/2efa8ca5-7569-4447-953a-74b7beea5cf6

**Comment by ryanfleury** [comment]
I'm having difficulty reproducing this on my end, so a couple of pieces of information (while the debugger is not properly reloading changes) would help:

- If you hit Ctrl + I (or run the `Switch` command), what does the list of files look like?
- If you attach to RADDBG with a debugger, and locate the thread with the `txti_detector_thread_entry_point` callstack, is that thread hung anywhere?

I'll also reintroduce the manual "Reload" command. That will ideally let you get out of this situation manually - or, if it doesn't work, then we've narrowed down where the bug is further.

**Comment by DevAgu93** [comment]
List of files:

![image](https://github.com/EpicGames/raddebugger/assets/63572671/02d88977-0882-4ae2-bf91-dff24cc2a5c6)

I'm sorry but I don't understand what you mean for the second piece of info. This happens even while not debugging.

**Comment by DevAgu93** [comment]
A bit of info:
·I made sure this is the latest release.
·This happens with every file.

**Comment by ryanfleury** [comment]
I just mean attaching to the debugger itself (e.g. via Remedy or VS), and seeing what the "check for file changes" thread is actually doing. If it is deadlocked or something like that, then that would be the bug.

**Comment by DevAgu93** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/63572671/884c8698-a90d-4eb5-a086-fc17ca50392a)

Again, apologies. Is this what you meant? Looks fine, no warning icons.

**Comment by ryanfleury** [comment]
Sorry for the delay here. I don't see any obvious issues in that screenshot, but the source view state/hot-reloading has now been ported to a new system. Do you still encounter the same issue if you build on `dev`?

**Comment by DevAgu93** [comment]
Hi Ryan.
It seems like the issue got fixed. Is this change on the current alpha release? If so, I can finally dump visual studio.

**Comment by ryanfleury** [comment]
Great to hear. Yep, it is! Let me know if you have any more issues with this.

**Comment by DevAgu93** [comment]
Thank you very much!
