### ISSUE TITLE
Program stops responding on conditional expression (inf 

### ISSUE THREAD

**Issue by alexgwalley** [EpicGamesExt/raddebugger#172]
![image](https://github.com/EpicGamesExt/raddebugger/assets/10475866/fe06b723-e069-44d5-9f16-1cf4fbb7c751)

The program stalls when I try to evaluate this expression in the watch window. 
The same happens when I try to use it as a conditional statement.

`context.entry_stack_first.v.resource.resourceType == 0xd8`

`context`, `stack_first`, and `resource` are all pointers
`resourceType` is an enum

the program doesn't crash when I try this expression:
`context.entry_stack_first.v.resource.resourceType == native_fhir::nf_fhir_r4::Bundle_Entry`
however, it doesn't give me a result either (should be true)
![image](https://github.com/EpicGamesExt/raddebugger/assets/10475866/63048936-60a1-409f-9d75-b5d2ca43dc82)

**Comment by ryanfleury** [comment]
Can you try this again on the latest 0.9.9 release, and let me know if the issue is still occurring? I can't reproduce it with the same type structure, it seems to evaluate fine.

Comparing to the enum failing (not hanging, but not showing any result) is just my lack of support for evaluating enum names; I will add that in.

**Comment by ryanfleury** [comment]
This issue should be resolved at this point, but just let me know if you spot it again.
