### ISSUE TITLE
Large Sized Disassembly in Watch View overflows the next Watch Row.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#222]
If you try to view a large sized disassembly (large byte size) in the watch view it will be displayed like this - visual overflowing into the next watch rows.
![disasm](https://github.com/EpicGamesExt/raddebugger/assets/105329747/1b999fa3-0039-4ba5-898e-2be7630c550f)

**Comment by ryanfleury** [comment]
Yeah, needless to say really, the disassembly visualizer (and basically every complex visualizer) is still heavily "under construction". I'll update this thread when this is further along.

**Comment by ryanfleury** [comment]
This is now fixed on `dev`, where the disassembly visualizer is identical to the regular disassembly tab UI. This will be in 0.9.12. I don't recommend pulling from `dev` just yet, since there are a few broken things I am still fixing before release, but nonetheless this fix will be in the next build.
