### ISSUE TITLE
Can't click to add breakpoint if stopped on that line.

### ISSUE THREAD

**Issue by mistymntncop** [EpicGamesExt/raddebugger#229]
If you are stopped on a particular line and that line doesn't have a breakpoint attached to it then you can't actually add a breakpoint to it by clicking the arrow area.
![image](https://github.com/EpicGamesExt/raddebugger/assets/105329747/5de7acee-fe3f-4ca0-a21b-3a43181a920f)

**Comment by ryanfleury** [comment]
Yeah, this has been submitted before. Because the thread IP arrow itself has important operations (double-click, drag/drop, right-click), and because several things (multiple threads, multiple breakpoints, multiple watch pins) can be stacked on a single line, my decision was to divide that margin only among what is already there when *necessary*, but to still offer a slower path for adding more to the line. In my mind, it is not a very intuitive/easy-to-use mechanism to click e.g. a smaller subdivision of the margin to add a breakpoint, if something (a thread's IP arrow) is already there.

In this case, you can still add a breakpoint with the mouse by right-clicking the line, and hitting "Place Breakpoint":
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/bfcdfc92-4b3e-4ef6-9a21-3c9bf4abf74a)

Or by running the "Toggle Breakpoint at Cursor" command (F9 by default):
![image](https://github.com/EpicGamesExt/raddebugger/assets/12454169/efefe7fb-c484-43df-a897-bfa6232b0569)

Or by placing a breakpoint elsewhere, and drag-dropping it to the line of your choice:
![DTL2nNyxMS](https://github.com/EpicGamesExt/raddebugger/assets/12454169/252fe852-a705-450b-b93d-a445d3ed685c)
