### ISSUE TITLE
Wrong values in watch

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#273]
Shows wrong values in watch and hover.
Build: 0.9.10 ALPHA [c60d3aa]

<img width="556" alt="image" src="https://github.com/EpicGamesExt/raddebugger/assets/29519295/dbeb2cc9-2811-4506-913e-97cece1706a5">

**Comment by MohitSethi99** [comment]
Shows correct values if optimizations are disabled.

**Comment by ryanfleury** [comment]
I expect that this is occurring due to a new location information case, which unoptimized builds do not produce. Is it possible for you to send me the PDB & RDI files for this build, as well as the function name where this is located? That will let me deduce what the PDB is producing and why it is either being misconverted or misused in the debugger.

**Comment by MohitSethi99** [comment]
Sadly I can't share any of that but I'll try to repro on my end and share my findings. Again, sorry about that.

**Comment by GloriousPtr** [comment]
Haven't encountered this in months, closing the issue.
