### ISSUE TITLE
Child members are not shown in watch when Parent is evaluated

### ISSUE THREAD

**Issue by GloriousPtr** [EpicGamesExt/raddebugger#300]
Raddbg:
![image](https://github.com/user-attachments/assets/5ac64f19-7eaf-45a8-9955-3d3ffecc2fc7)

VS:
![image](https://github.com/user-attachments/assets/6d871e07-11c7-4f4d-9358-e36300a624b5)

**Comment by GloriousPtr** [comment]
Can up this? A bit of a bummer that this bug exists 🥲

**Comment by ryanfleury** [comment]
This should work on `master` - if you are on `dev`, I would recommend temporarily switching back to `master`, since `dev` is a bit in flux at the moment, including in the "eval visualization" system, which directly impacts this issue. I appreciate you bringing this to my attention, though - before 0.9.12 (which should be soon), I will triple check that this works.

**Comment by ryanfleury** [comment]
Fixed now in `dev`. Let me know if you run into any more issues with this. This will be in 0.9.12 also.
