### ISSUE TITLE
arena_pop doesn't work correctly when arenas are chained

### ISSUE THREAD

**Issue by minh0722** [EpicGamesExt/raddebugger#333]
Tested with this code chunk. first two times arena_pop works fine, but on the third time it just releases the chained arena without actually offsetting the first arena pos for the requested pop

```
typedef struct
{
    U32 str[128];
} Obj;

Arena* test = arena_alloc(.reserve_size = KB(32), .commit_size = KB(4));

for(U32 i = 0; i < 65; ++i)
{
    Obj* ptr = push_array(test, Obj, 1);
    memset(ptr, i+1, 128 * sizeof(U32));
}

for(int i = 0; i < 65; ++i)
{
    arena_pop(test, sizeof(Obj));
}

```

**Comment by ryanfleury** [comment]
This is not a bug; the first arena in the chain does not need its position changed.

On the 64th push, before the chain occurs, the arena's position is `32320`. The 64th push does not fit in the remaining space. So a new arena is chained onto the first, and the 64th push is allocated there. The first arena's position still does not change when this happens; the remaining space is not used, and so it isn't completely full, but this is not relevant, because when a subsequent push occurs, it will not use `arena`, but `arena->current`, which now points at the second node in the chain.

When you pop the 65th and 64th `Obj`s, the arena just resets back to what it was before the 64th push - which is just one arena in the chain, at position `32320`.

**Comment by minh0722** [comment]
Hmm, so arena_pop isn't exactly free() in the sense that a memory allocation is freed but just a state revert? I'd imagined that in the way that is used in my example, user would expect that memory for 65 Objs were "freed".

**Comment by ryanfleury** [comment]
It's wrong to say it's like `free`, since an arena is a linear/bump/stack allocator mechanism, but it's true that the space used for the 65 `Obj`s is all freed. An `Arena` is not just a single arena; it is a chain of `Arena`s. Each `Arena`'s `pos` member is the *relative position* of that node in the `Arena` chain. In order to calculate the full position of a full `Arena` chain, you need to calculate `arena->current->base_pos + arena->current->pos`. If you calculate that, you'll see that the "global" position decreases on every single pop.

**Comment by minh0722** [comment]
Ah ok, I get what you mean. I was thinking from the pov of element removal whereas here it's correctly offsetting memory position.
That's kind of a disclaimer to be careful of when used in the way in my example, because from the looks of it, 64 elements were actually removed. But maybe it's not the correct way to use it, instead to always reserve enough memory to contain the whole array.

**Comment by ryanfleury** [comment]
Popping always works, but yeah generally the patterns we use in the codebase are popping *to* some previous position, to end a lifetime. It isn't normally used for data structure back-element removal. In this case, it is not even an array, because the arenas are chained, and so the 64th `Obj` is discontiguous from the 63rd.

**Comment by minh0722** [comment]
`it is not even an array, because the arenas are chained, and so the 64th Obj is discontiguous from the 63rd.`

(facepalm) You're right, totally forgot about this property...
Thanks for the explanation. Learning a lot from this project
