### ISSUE TITLE
Attempt to launch debuuger after previous debug session.

### ISSUE THREAD

**Issue by Wc4ever** [EpicGamesExt/raddebugger#351]
[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue at
https://github.com/EpicGamesExt/raddebugger/issues

Call stack:
1. [0x7ff7e82fc7dd] rd_code_view_build +12381, raddbg_views.c line 632
2. [0x7ff7e82474fc] rd_view_rule_ui_output +876, raddbg_views.c line 6326
3. [0x7ff7e836a8d2] rd_window_frame +185458, raddbg_core.c line 7628
4. [0x7ff7e831ccda] rd_frame +94618, raddbg_core.c line 16696
5. [0x7ff7e82b0a35] entry_point +8597, raddbg_main.c line 972
6. [0x7ff7e83b30e8] w32_entry_point_caller +2536, os_core_win32.c line 1676
7. [0x7ff7e83b319d] wWinMain +29, os_core_win32.c line 1689
8. [0x7ff7e83b42b2] __scrt_common_main_seh +262, exe_common.inl line 288
9. [0x7ff8b0bf7374] KERNEL32
10. [0x7ff8b10dcc91] ntdll

Version: 0.9.13 [f792da5]

**Comment by ryanfleury** [comment]
I've just pushed a fix to `dev` for this, can you try pulling & building from the top of `dev` and tell me if this issue is fixed?

**Comment by ryanfleury** [comment]
I think this just had to do with having changed a source file to no longer contain the cursor's saved position. It should be fixed now but let me know if you run into it again.

**Comment by zshoals** [comment]
I figured I'd mention this here, I was encountering this issue as well on an older revision and it seems to be fixed in the current build. I triggered this issue by accidentally (woops...) dumping 100k separate lines of text into the output pane. Restarting raddbg afterwards resulted in this crash. It seemed to have to do with the default.raddbg_user file storing the output view's "cursor_line" and "mark_line" values. High stored line positions (in my case, ~100k) seemed to cause the crash. Resetting both to 1 fixed it.
